/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/add-instrument': RouteRecordInfo<'/add-instrument', '/add-instrument', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/instruments/[id]/details': RouteRecordInfo<'/instruments/[id]/details', '/instruments/:id/details', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/instruments/[id]/management/location': RouteRecordInfo<'/instruments/[id]/management/location', '/instruments/:id/management/location', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/instruments/[id]/management/repair': RouteRecordInfo<'/instruments/[id]/management/repair', '/instruments/:id/management/repair', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
